image: selu383envoc/383build

options:
  max-time: 15
pipelines:
  default:
    - step:
        name: "Build/Test Web"
        script:
          - sleep 10
          - dotnet test FA20.P05.Tests.Web
        services:
          - sqlserver
    - step:
        name: "Build/Test Mobile"
        deployment: test-mobile
        image: node:alpine
        caches:
          - npm
        script:
          - apk add --no-cache bash
          - cd FA20-P05-Mobile
          - npm install -g expo-cli
          - yarn install --frozen-lockfile
          - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          - expo publish --non-interactive --release-channel ci

  branches:
    master:
      - step:
          name: "Build/Test/Publish Web"
          script:
            - apt-get update
            - apt-get install --yes zip
            - sleep 10
            - dotnet test FA20.P05.Tests.Web
            - dotnet publish FA20.P05.Web --output publish
            - cd publish && zip -r web-$BITBUCKET_BUILD_NUMBER.zip .
          services:
            - sqlserver
          artifacts:
            - publish/*.zip
      - step:
          name: "Deploy Web to Azure"
          deployment: test
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: "fa20-p05-g02"
                AZURE_APP_NAME: "selu383-fa20-p05-g02"
                ZIP_FILE: "publish/web-$BITBUCKET_BUILD_NUMBER.zip"
      - step:
          name: "Check Health"
          script:
            - curl -sSf https://selu383-fa20-p05-g02.azurewebsites.net/api/schools/active
      - step:
          name: "Deploy Mobile to Expo"
          deployment: test-mobile
          image: node:alpine
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - cd FA20-P05-Mobile
            - npm install -g expo-cli
            - yarn install --frozen-lockfile
            - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - expo publish --non-interactive
            - expo build:android -t apk --no-wait --non-interactive

definitions:
  caches:
    npm: ~/.npm
  services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04
      memory: 2048
      variables:
        ACCEPT_EULA: Y
        SA_PASSWORD: Password123!
